# Generated by Django 3.2.19 on 2023-05-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="../default_profile_enctdp_kyu1a7", upload_to="images/"
            ),
        ),
    ]
